# Generated by Django 5.2.3 on 2025-07-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
